-- Enable UUID extension
create extension if not exists "uuid-ossp";
-- Users Table
create table public.users (
    id bigint generated by default as identity primary key,
    name text,
    identifier text unique not null,
    password text,
    role text default 'customer',
    created_at timestamp with time zone default timezone('utc'::text, now())
);
-- Products Table
create table public.products (
    id bigint generated by default as identity primary key,
    name text not null,
    price numeric not null,
    category text,
    image text,
    description text,
    stock int default 0,
    created_at timestamp with time zone default timezone('utc'::text, now())
);
-- Orders Table
create table public.orders (
    id bigint generated by default as identity primary key,
    user_identifier text references public.users(identifier),
    -- Linking by email/identifier for simplicity as per current logic
    items jsonb,
    total numeric,
    status text default 'pending',
    created_at timestamp with time zone default timezone('utc'::text, now())
);
-- Collections Table
create table public.collections (
    id bigint generated by default as identity primary key,
    title text,
    image text,
    link text,
    text_position text,
    text_color text,
    created_at timestamp with time zone default timezone('utc'::text, now())
);
-- Offers Table
create table public.offers (
    id bigint generated by default as identity primary key,
    title text,
    discount_percentage numeric,
    description text,
    image text,
    created_at timestamp with time zone default timezone('utc'::text, now())
);
-- Hero Slides Table
create table public.hero_slides (
    id bigint generated by default as identity primary key,
    image text,
    caption text,
    created_at timestamp with time zone default timezone('utc'::text, now())
);
-- Enable Row Level Security (RLS) - Optional: Disable for now to keep it simple like db.json
alter table public.users enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.collections enable row level security;
alter table public.offers enable row level security;
alter table public.hero_slides enable row level security;
-- Create Policies (Allow Public Read/Write for this migration phase, verify later)
-- CAUTION: This is for development. In production, lock this down.
create policy "Public Access" on public.users for all using (true);
create policy "Public Access" on public.products for all using (true);
create policy "Public Access" on public.orders for all using (true);
create policy "Public Access" on public.collections for all using (true);
create policy "Public Access" on public.offers for all using (true);
create policy "Public Access" on public.hero_slides for all using (true);